#!/bin/bash

# change to the dir of the script
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Generate the github pages documentation for this project. The documentation for core/Rearrangement is generated by doxygen. bash shells are transformed to executable markdown by the track at https://gist.github.com/bwoods/1c25cb7723a06a076c2152a2781d4d49. awk and perl scripts are wrapped by the corresponding code block in markdown.

name_to_link()
{
    local query="$1"
    local lines
    readarray lines < <(yq -c '.[]' < docs/_data/navigation.yml)
    while [ ${#lines[@]} -gt 0 ]
    do
        local line="${lines[0]}"
        lines=("${lines[@]:1}")
        local name=$(yq -r '.name' <<<${line})
        local link=$(yq -r '.link' <<<${line})
        if ! [ "${link}" = "null" ]
        then
            name2link["${name}"]=$(sed 's/^/docs/;s/html$/md/' <<<"${link}")
        fi
        local sub=$(yq '.sub' <<<${line})
        if ! [ "${sub}" = "null" ]
        then
            local sublines
            readarray sublines < <(yq -c '.[]' <<< "${sub}")
            lines=("${sublines[@]}" "${lines[@]}")
        fi
    done
}

add_header()
{
    local name=$1
    local copy_path=${name2link["${name}"]}
    mkdir -p $(dirname "${copy_path}")
    sed "1i ---\ntitle: \"${name}\"\n---\n\n" \
        > "${copy_path}"
}

wrap_script()
{
    local script_type=$1
    sed -e '1i {% highlight '$script_type' linenos %}' -e '$a {% endhighlight %}'
}

# Failure stop the execution.
set -e

# Initialize name2link
declare -A name2link
name_to_link

########################
# core
########################

add_header "Core" \
    < core/Rearrangement/core.md

mkdir -p docs/core/rearr
cd core/Rearrangement
doxygen
cd -

wrap_script awk \
    < core/Rearrangement/correct_micro_homology.awk |
add_header "CMH"

########################
# auxilary
########################

add_header "RmDup" \
    < core/removeDuplicates.sh

add_header "Demultiplex" \
    < core/demultiplex/demultiplex.sh

wrap_script awk \
    < core/demultiplex/getAlignPos.awk |
add_header "GetAlignPos"

########################
# workflow
########################

add_header "RunWorkFlow" \
    < runWorkFlow.sh

wrap_script make \
    < workFlow.mak |
add_header "WorkFlow"

########################
# in-house
########################

add_header "SxExtractSpliter" \
    < sx/sxExtractSpliter.sh

add_header "SxCutR2AdapterFilterCumulate" \
    < sx/sxCutR2AdapterFilterCumulate/sxCutR2AdapterFilterCumulate.sh

wrap_script awk \
    < sx/sxCutR2AdapterFilterCumulate/sxCumulateToMapCutAdaptSpliter.awk |
add_header "SxCumulateToMapCutAdaptSpliter"

add_header "GetSxCsvFileRef" \
    < sx/getSxCsvFileRef/getSxCsvFileRef.sh
    
wrap_script perl \
    < sx/getSxCsvFileRef/getSxCsvFileTarget.pl |
add_header "GetSxCsvFileTarget"

wrap_script awk \
    < sx/getSxCsvFileRef/sxTargetSam2Bed.awk |
add_header "SxTargetSam2Bed"

wrap_script perl \
    < sx/getSxCsvFileRef/getSxRefFile.pl |
add_header "GetSxRefFile"
