#!/bin/bash

# change to the dir of the script
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Generate the github pages documentation for this project. The documentation for core/Rearrangement is generated by doxygen. bash shells are transformed to executable markdown by the track at https://gist.github.com/bwoods/1c25cb7723a06a076c2152a2781d4d49. awk and perl scripts are wrapped by the corresponding code block in markdown.

name_to_link()
{
    local query_name=$1
    local line
    local name
    local link
    while read line
    do
        IFS="," read name link <<<$line
        if [ "$query_name" = "$name" ]
        then
            echo $link | sed 's/^/docs/;s/html$/md/'
            return
        fi
    done < <(
        yq -c ".[]" docs/_data/navigation.yml | sed -r 's/\{"name":"(.+)","link":"(.+)"\}/\1,\2/'
    )
    exit 1
}

add_header()
{
    local name=$1
    local copy_path=$(name_to_link "${name}")
    mkdir -p $(dirname "${copy_path}")
    sed "1i ---\nlayout: default\ntitle: \"${name}\"\n---\n\n" \
        > "${copy_path}"
}

wrap_script()
{
    local script_type=$1
    sed -e '1i {% highlight '$script_type' linenos %}' -e '$a {% endhighlight %}'
}

# Failure stop the execution.
set -e

add_header "RmDup" \
    < core/removeDuplicates.sh

# add_header "Demultiplex" "/core/demultiplex/" < core/demultiplex/demultiplex.sh > docs/_docs/demultiplex.sh.md
# wrap_script awk < core/demultiplex/getAlignPos.awk | add_header "Get alignment position" "/core/demultiplex/get-alignment-position/" > docs/_docs/getAlignPos.awk.md

add_header "Rearr" \
    < core/Rearrangement/rearr.md

mkdir -p docs/core/rearr
cd core/Rearrangement
doxygen
cd -

wrap_script awk \
    < core/Rearrangement/correct_micro_homology.awk |
add_header "CMH"

# add_header "Shi Xing extract spliter" "/sx/sx-extract-spliter/" < sx/sxExtractSpliter.sh > docs/_docs/sxExtractSpliter.sh.md

# add_header "Shi Xing post-process from demultiplex to rearr" "/sx/sx-cut-r2-adapter-filter-cumulate/" < sx/sxCutR2AdapterFilterCumulate/sxCutR2AdapterFilterCumulate.sh > docs/_docs/sxCutR2AdapterFilterCumulate.sh.md
# wrap_script awk < sx/sxCutR2AdapterFilterCumulate/sxCumulateToMapCutAdaptSpliter.awk | add_header "Accumulate adjacent duplicated queries" "/sx/sx-cut-r2-adapter-filter-cumulate/sx-cumulate-to-map-cut-adapt-spliter/" > docs/_docs/sxCumulateToMapCutAdaptSpliter.awk.md

# add_header "Get Shi Xing csvfile reference" "/sx/get-sx-csvfile-ref/" < sx/getSxCsvFileRef/getSxCsvFileRef.sh > docs/_docs/getSxCsvFileRef.sh.md
# wrap_script perl < sx/getSxCsvFileRef/getSxCsvFileTarget.pl | add_header "Get Shi Xing csvfile target" "/sx/get-sx-csvfile-ref/get-sx-csvfile-target/" > docs/_docs/getSxCsvFileTarget.pl.md
# wrap_script awk < sx/getSxCsvFileRef/sxTargetSam2Bed.awk | add_header "Shi Xing target sam to bed" "/sx/get-sx-csvfile-ref/sx-target-sam-2-bed/" > docs/_docs/sxTargetSam2Bed.awk.md
# wrap_script perl < sx/getSxCsvFileRef/getSxRefFile.pl | add_header "Get Shi Xing reference file" "/sx/get-sx-csvfile-ref/get-sx-ref-file/" > docs/_docs/getSxRefFile.pl.md

add_header "RunWorkFlow" \
    < runWorkFlow.sh

wrap_script make \
    < workFlow.mak |
add_header "WorkFlow"
