services:
  flower:
    depends_on:
      - rabbitmq
    container_name: celery_flower
    image: my_celery_flower
    ports:
      - "5555:5555"
    command: ["celery", "-A", "celery_project.app", "--broker=amqp://rabbitmq:5672", "flower"]

  rabbitmq:
    container_name: celery_rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"

  worker:
    depends_on:
      - rabbitmq
    container_name: celery_worker
    image: my_celery_worker
    volumes:
      - "./flask_project/tmp:/app/tmp"
    command: ["celery", "-A", "celery_project.app", "--broker=amqp://rabbitmq:5672", "worker"]

  shiny:
    container_name: shiny_server
    build:
      context: .
      dockerfile: ./shiny_server.df
    image: my_shiny_server
    ports:
      - "3838:3838"
    volumes:
      - "./shinyApps:/srv/shiny-server"
