#!/bin/bash
# use "less -SNR ljhlyz/AN1-SG4-M1B-1-1_R1.fq.gz" to see the alignment

ref="CTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGTTGCTGTTGCTGGTGGTGATGGTGATGTGTTGAGACTGGTGGGTGGGCGGTGGACTGGGCCCCAGTAGAGGGAGGGAAGGGGCCTGGATGGGCATTGCTGTT"
python ljhlyz/test.py ljhlyz/AN1-SG4-M1B-1-1_R1.fq.gz $ref 82 30 True