name: Unit test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
            conda install conda-forge::sed conda-forge::gawk bioconda::samtools bioconda::bedtools bioconda::bowtie2
            pip install numpy cutadapt

      - name: Run unit test
        run: python -m unittest test.test_suite_no_genome
