name: Unit test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo ./install.md core sx

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Unit test
        run: python -m unittest